import {
  LayoutDashboard,
  Users,
  UserPlus,
  CalendarClock,
  Trophy,
  UsersRound,
  FileText,
  BarChart3,
  Calendar,
  Bell,
  User,
  MapPin,
  Award,
  Mail,
  Percent,
} from 'lucide-react';

/** Sales Manager sidebar — matches Command Center mockup sections */
export const salesManagerNavItems = [
  { path: '/sales-manager/dashboard', label: 'Dashboard', icon: LayoutDashboard, section: 'Lead Management' },
  {
    path: '/sales-manager/leads/all',
    label: 'Lead Management',
    icon: Users,
    badgeKey: 'leads.all',
    countKey: 'leads.all',
    section: 'Lead Management',
  },
  { path: '/sales-manager/email-activity', label: 'Email Activity', icon: Mail, section: 'Lead Management' },
  {
    path: '/sales-manager/assignment',
    label: 'Lead Assignment',
    icon: UserPlus,
    badgeKey: 'leads.unassigned',
    section: 'Lead Management',
  },
  {
    path: '/sales-manager/destination-assignment',
    label: 'Destination Assignment',
    icon: MapPin,
    section: 'Lead Management',
  },
  {
    path: '/sales-manager/skill-assignment',
    label: 'Skill Assignment',
    icon: Award,
    section: 'Lead Management',
  },
  {
    path: '/sales-manager/margin-control',
    label: 'Margin Control',
    icon: Percent,
    section: 'Lead Management',
  },
  {
    path: '/sales-manager/teams',
    label: 'Team Management',
    icon: UsersRound,
    section: 'Sales Operations',
  },
  {
    path: '/sales-manager/follow-ups',
    label: 'Follow-up Monitoring',
    icon: CalendarClock,
    badgeKey: 'followups.due',
    section: 'Sales Operations',
  },
  {
    path: '/sales-manager/team',
    label: 'Sales Targets',
    icon: Trophy,
    section: 'Sales Operations',
  },
  {
    path: '/sales-manager/quotations/pending',
    label: 'Quotations',
    icon: FileText,
    badgeKey: 'quotations.pending',
    section: 'Sales Operations',
  },
  {
    path: '/sales-manager/reports',
    label: 'Reports',
    icon: BarChart3,
    section: 'Sales Operations',
  },
  {
    path: '/sales-manager/calendar',
    label: 'Calendar',
    icon: Calendar,
    badgeKey: 'calendar.today',
    section: 'Support & Tools',
  },
  {
    path: '/sales-manager/notifications',
    label: 'Notifications',
    icon: Bell,
    badgeKey: 'notifications.unread',
    section: 'Support & Tools',
  },
  {
    path: '/sales-manager/profile',
    label: 'Profile',
    icon: User,
    section: 'Support & Tools',
  },
];
