import API from '../api/axios';

export const hrApi = {
  dashboard: () => API.get('/hr/dashboard', { skipSuccessToast: true }).then((r) => r.data),
  employees: (params) => API.get('/hr/employees', { params, skipSuccessToast: true }).then((r) => r.data),
  employee: (id) => API.get(`/hr/employees/${id}`, { skipSuccessToast: true }).then((r) => r.data),
  createEmployee: (body) => API.post('/hr/employees', body).then((r) => r.data),
  updateEmployee: (id, body) => API.put(`/hr/employees/${id}`, body).then((r) => r.data),
  deleteEmployee: (id) => API.delete(`/hr/employees/${id}`).then((r) => r.data),
  departments: () => API.get('/hr/departments', { skipSuccessToast: true }).then((r) => r.data),
  createDepartment: (body) => API.post('/hr/departments', body).then((r) => r.data),
  updateDepartment: (id, body) => API.put(`/hr/departments/${id}`, body).then((r) => r.data),
  deleteDepartment: (id) => API.delete(`/hr/departments/${id}`).then((r) => r.data),
  designations: (params) => API.get('/hr/designations', { params, skipSuccessToast: true }).then((r) => r.data),
  createDesignation: (body) => API.post('/hr/designations', body).then((r) => r.data),
  updateDesignation: (id, body) => API.put(`/hr/designations/${id}`, body).then((r) => r.data),
  deleteDesignation: (id) => API.delete(`/hr/designations/${id}`).then((r) => r.data),
  holidays: (params) => API.get('/hr/holidays', { params, skipSuccessToast: true }).then((r) => r.data),
  createHoliday: (body) => API.post('/hr/holidays', body).then((r) => r.data),
  deleteHoliday: (id) => API.delete(`/hr/holidays/${id}`).then((r) => r.data),
  leaves: (params) => API.get('/hr/leaves', { params, skipSuccessToast: true }).then((r) => r.data),
  createLeave: (body) => API.post('/hr/leaves', body).then((r) => r.data),
  reviewLeave: (id, body) => API.patch(`/hr/leaves/${id}/review`, body).then((r) => r.data),

  salaryStructures: () => API.get('/hr/salary-structures', { skipSuccessToast: true }).then((r) => r.data),
  createSalaryStructure: (body) => API.post('/hr/salary-structures', body).then((r) => r.data),
  updateSalaryStructure: (id, body) => API.put(`/hr/salary-structures/${id}`, body).then((r) => r.data),
  deleteSalaryStructure: (id) => API.delete(`/hr/salary-structures/${id}`).then((r) => r.data),

  payrollRuns: (params) => API.get('/hr/payroll', { params, skipSuccessToast: true }).then((r) => r.data),
  payrollRun: (id) => API.get(`/hr/payroll/${id}`, { skipSuccessToast: true }).then((r) => r.data),
  createPayrollRun: (body) => API.post('/hr/payroll', body).then((r) => r.data),
  updatePayrollStatus: (id, body) => API.patch(`/hr/payroll/${id}/status`, body).then((r) => r.data),
  deletePayrollRun: (id) => API.delete(`/hr/payroll/${id}`).then((r) => r.data),

  documents: (params) => API.get('/hr/documents', { params, skipSuccessToast: true }).then((r) => r.data),
  createDocument: (body) => API.post('/hr/documents', body).then((r) => r.data),
  deleteDocument: (id) => API.delete(`/hr/documents/${id}`).then((r) => r.data),

  assets: (params) => API.get('/hr/assets', { params, skipSuccessToast: true }).then((r) => r.data),
  createAsset: (body) => API.post('/hr/assets', body).then((r) => r.data),
  assignAsset: (id, body) => API.post(`/hr/assets/${id}/assign`, body).then((r) => r.data),
  returnAsset: (id, body) => API.post(`/hr/assets/${id}/return`, body).then((r) => r.data),
  deleteAsset: (id) => API.delete(`/hr/assets/${id}`).then((r) => r.data),

  expenses: (params) => API.get('/hr/expenses', { params, skipSuccessToast: true }).then((r) => r.data),
  createExpense: (body) => API.post('/hr/expenses', body).then((r) => r.data),
  reviewExpense: (id, body) => API.patch(`/hr/expenses/${id}/review`, body).then((r) => r.data),
  deleteExpense: (id) => API.delete(`/hr/expenses/${id}`).then((r) => r.data),

  performance: (params) => API.get('/hr/performance', { params, skipSuccessToast: true }).then((r) => r.data),
  createPerformance: (body) => API.post('/hr/performance', body).then((r) => r.data),
  updatePerformance: (id, body) => API.put(`/hr/performance/${id}`, body).then((r) => r.data),
  deletePerformance: (id) => API.delete(`/hr/performance/${id}`).then((r) => r.data),

  jobs: (params) => API.get('/hr/jobs', { params, skipSuccessToast: true }).then((r) => r.data),
  createJob: (body) => API.post('/hr/jobs', body).then((r) => r.data),
  updateJob: (id, body) => API.put(`/hr/jobs/${id}`, body).then((r) => r.data),
  deleteJob: (id) => API.delete(`/hr/jobs/${id}`).then((r) => r.data),

  candidates: (params) => API.get('/hr/candidates', { params, skipSuccessToast: true }).then((r) => r.data),
  recruitmentFunnel: () => API.get('/hr/candidates/funnel', { skipSuccessToast: true }).then((r) => r.data),
  createCandidate: (body) => API.post('/hr/candidates', body).then((r) => r.data),
  updateCandidate: (id, body) => API.put(`/hr/candidates/${id}`, body).then((r) => r.data),
  deleteCandidate: (id) => API.delete(`/hr/candidates/${id}`).then((r) => r.data),

  interviews: (params) => API.get('/hr/interviews', { params, skipSuccessToast: true }).then((r) => r.data),
  createInterview: (body) => API.post('/hr/interviews', body).then((r) => r.data),
  updateInterview: (id, body) => API.put(`/hr/interviews/${id}`, body).then((r) => r.data),
  deleteInterview: (id) => API.delete(`/hr/interviews/${id}`).then((r) => r.data),

  incentives: (params) => API.get('/hr/incentives', { params, skipSuccessToast: true }).then((r) => r.data),
  createIncentive: (body) => API.post('/hr/incentives', body).then((r) => r.data),
  reviewIncentive: (id, body) => API.patch(`/hr/incentives/${id}/review`, body).then((r) => r.data),
  deleteIncentive: (id) => API.delete(`/hr/incentives/${id}`).then((r) => r.data),
};
